name: Custom Workflow

on: 
  workflow_dispatch:
    inputs:
      terraform_command:
        description: 'Terraform command'
        required: true
        default: 'terraform plan'
      relative_dir_to_terraform_code:
        description: 'Relative path to terraform code'
        required: true
        default: './infra/databricks/workflows/partner_affiliate_data_raw_to_bronze'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Run the terraform command
        run: |
          echo "Running terraform command "
          echo "${{ github.event.inputs.terraform_command }} ${{ github.event.inputs.relative_dir_to_terraform_code }} "
